apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsprojectexample-testfile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopsprojectexample-testfile
  template:
    metadata:
      labels:
        app: devopsprojectexample-testfile
    spec:
      containers:
        - name: devopsprojectexample-testfile-app
          image: thegangg/devopsprojectexample-testfile:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
