apiVersion: apps/v1
kind: Deployment
metadata:
  name: DevOpsProjectExample-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: DevOpsProject-app
  template:
    metadata:
      labels:
        app: DevOpsProject-app
    spec:
      containers:
        - name: DevOpsProject-app
          image: thegangg/devopsprojectexample-testfile:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
