apiVersion: v1
kind: Service
metadata:
  name: devopsprojectexample-service
  labels:
    app: DevOpsProject-app
spec:
  selector:
    app: DevOpsProject-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
