apiVersion: v1
kind: Service
metadata:
  name: devopsprojectexample-service
  labels:
    app: devopsprojectexample-testfile
spec:
  selector:
    app: devopsprojectexample-testfile

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
